- hosts: localhost
  connection: local
  tasks:
   - name: resize instances { RDS }
     rds:
       command: modify
       instance_name: "{{instance_name}}"
       instance_type: "{{instance_type}}"      
       aws_access_key: "{{access_key}}"
       aws_secret_key: "{{secret_key}}"
       region: ap-south-1
       wait: yes
       apply_immediately: yes
    
   - pause:
       seconds: 40
 
   - name: get fact for instance availble state
     rds:
       command: facts
       instance_name: "{{instance_name}}"
       aws_access_key: "{{access_key}}"
       aws_secret_key: "{{secret_key}}"
       region: ap-south-1
     register: new_facts
     until: new_facts.instance.status == "available"
     retries: 25
     delay: 60
